Tweak
DilsherB/OOP-schoolLibrary-Ruby pull request #20
Opened 2023-07-29 06:02 UTC by DilsherB

## Highlights of this PR

1. arrange the files in a more organized way
2. change paths in `require_relative` wherever necessary.
3. make sure functionality has not broken
4. update the readme to clarify the project more meaningfully.

2023-07-31 14:25 UTC, Davidosky007 reviewed
Hi @DilsherB 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't show contribution from your partner as this is a paired programming activity you are expected to work together with your coding partner 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-07-31 16:33 UTC, Davidosky007 requested changes
Hi @DilsherB @berylcl 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
## Highlights
* No linter errors 👍 
* Well written PR 👍 
* Good looking readme 👍 
* Ruby code refactored 👍 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @davidsoky007 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-31 16:33 UTC, Davidosky007 commented on app/app.rb
> +    print "1 to create a student\n2 to create a teacher\n [Input the number]:"
* Kindly ensure that `all requests for input and input validation should've been placed in the main.rb file and/or classes/methods whose responsibilities are to request or validate input`

2023-07-31 17:42 UTC, DilsherB commented on app/app.rb
> +    print "1 to create a student\n2 to create a teacher\n [Input the number]:"
@Davidosky007 , I couldn't understand your objection. Would you please help me to understand what is the requirement.

2023-07-31 18:37 UTC, DilsherB commented on app/app.rb
> +    print "1 to create a student\n2 to create a teacher\n [Input the number]:"
changes implemented.

2023-07-31 19:05 UTC, Gambit142 requested changes
Hi @DilsherB @berylcl 👋, 

Great work on making the changes requested by a previous reviewer 👏 

## Highlights
- All linters checks passed ✔️ 
- README file is professional ✔️ 

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer and addressing them will improve your application._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-31 19:05 UTC, Gambit142 commented on app/app.rb
> +    puts "🎉 Book '#{title}' created successfully"
- [ ] The previous reviewer requested that all codes responsible for receiving inputs or codes responsible for validating the input from the user should be put in the main.rb file or a separate class or class method or module. The other methods for creating a class instance or listing instances should only create those instances. 👍 😎 

---

For Example, the `create_student` method should only create a new instance of the `Student` class while codes for getting the `name`, `age` and `parent_permission` of the _**student**_ should be put in a separate method, class or module. 💻 

--- 

Kindly apply these changes for the following methods in the app.rb file:

- `create_student`
- `create_teacher`
- `create_book`
- `create_rental`

---

#### N.B: Please ensure that the app works as it should after refactoring the code. 👍

2023-08-01 01:42 UTC, Lizdev-05 requested changes
Hi Team, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media2.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif"/>

 ## Highlights
:heavy_check_mark: Professional Readme file :+1: 
:heavy_check_mark: Good commit history :+1:
:heavy_check_mark: No linter error :+1: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-01 01:42 UTC, Lizdev-05 commented on main.rb
> +    4 => :create_teacher,
- [ ] Per the previous code reviewer's request, please ensure your app functions properly. Instead of having the option "create a person" on the menu list, you have "create a student" and "create a teacher" options. Remember that your school library console app should behave similarly to the [example video](https://www.youtube.com/watch?v=vkkgrhD6aXQ)

2023-08-01 02:17 UTC, Lizdev-05 approved these changes
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

## Highlights

:heavy_check_mark: Professional Readme file :+1: 
:heavy_check_mark: Good commit history :+1:
:heavy_check_mark: No linter error :+1: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-01 02:24 UTC, merged